window.DRAGONDEX_DATA = {
  "set": {
    "code": "BT31",
    "name": "Impact Beyond Dimensions",
    "recordCount": 184,
    "baseCardCount": 151,
    "isComplete": false,
    "mainRecordCount": 174,
    "energyMarkerCount": 10,
    "includesEnergyMarkers": true
  },
  "cards": [
    {
      "id": "BT31-EM01_REGULAR",
      "number": "BT31-EM01",
      "name": "Energy Marker 01",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Regular",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM01_GOLD",
      "number": "BT31-EM01",
      "name": "Energy Marker 01",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Gold Stamped",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM02_REGULAR",
      "number": "BT31-EM02",
      "name": "Energy Marker 02",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Regular",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM02_GOLD",
      "number": "BT31-EM02",
      "name": "Energy Marker 02",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Gold Stamped",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM03_REGULAR",
      "number": "BT31-EM03",
      "name": "Energy Marker 03",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Regular",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM03_GOLD",
      "number": "BT31-EM03",
      "name": "Energy Marker 03",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Gold Stamped",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM04_REGULAR",
      "number": "BT31-EM04",
      "name": "Energy Marker 04",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Regular",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM04_GOLD",
      "number": "BT31-EM04",
      "name": "Energy Marker 04",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Gold Stamped",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM05_REGULAR",
      "number": "BT31-EM05",
      "name": "Energy Marker 05",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Regular",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-EM05_GOLD",
      "number": "BT31-EM05",
      "name": "Energy Marker 05",
      "rarity": "EM",
      "color": "",
      "type": "ENERGY MARKER",
      "variant": "Gold Stamped",
      "group": "energy",
      "verified": true
    },
    {
      "id": "BT31-001",
      "number": "BT31-001",
      "name": "Son Goku & Vegeta",
      "rarity": "UC",
      "color": "Red",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-001_PR",
      "number": "BT31-001_PR",
      "name": "Son Goku & Vegeta",
      "rarity": "SLR",
      "color": "Red",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-002",
      "number": "BT31-002",
      "name": "Janemba",
      "rarity": "UC",
      "color": "Red",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-002_PR",
      "number": "BT31-002_PR",
      "name": "Janemba",
      "rarity": "SLR",
      "color": "Red",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-003",
      "number": "BT31-003",
      "name": "SS Gogeta, Invincible Power",
      "rarity": "R",
      "color": "Red",
      "type": "Z-BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-004",
      "number": "BT31-004",
      "name": "Phantom Shift -Disintegration-",
      "rarity": "C",
      "color": "Red",
      "type": "Z-EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-005",
      "number": "BT31-005",
      "name": "Phantom Shift -Restoration-",
      "rarity": "C",
      "color": "Red",
      "type": "Z-EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-006",
      "number": "BT31-006",
      "name": "SS3 Gotenks, Wild Rampage",
      "rarity": "SR",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-007",
      "number": "BT31-007",
      "name": "SS3 Son Goku, Struggle in Another World",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-008",
      "number": "BT31-008",
      "name": "Son Goku, Other World Warrior",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-009",
      "number": "BT31-009",
      "name": "Son Goku, Training in Another World",
      "rarity": "UC",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-010",
      "number": "BT31-010",
      "name": "Son Goku & Vegeta, Battling Against Evil",
      "rarity": "UC",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-011",
      "number": "BT31-011",
      "name": "SS Vegeta, Struggle in Another World",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-012",
      "number": "BT31-012",
      "name": "Vegeta, Hellish Warrior",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-013",
      "number": "BT31-013",
      "name": "Veku, Incomplete Fusion",
      "rarity": "UC",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-014",
      "number": "BT31-014",
      "name": "SS Gogeta, Revoker of Evil",
      "rarity": "SR",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-015",
      "number": "BT31-015",
      "name": "SS Gogeta, Vanquisher",
      "rarity": "R",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-016",
      "number": "BT31-016",
      "name": "Janemba, Concentrated Hatred",
      "rarity": "SR",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-017",
      "number": "BT31-017",
      "name": "Janemba, Demonic Howl",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-018",
      "number": "BT31-018",
      "name": "Janemba, Unintentional Evil",
      "rarity": "UC",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-019",
      "number": "BT31-019",
      "name": "Janemba, Little Wicked Clones",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-020",
      "number": "BT31-020",
      "name": "Baby Janemba, the Abhorrent",
      "rarity": "SR",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-021",
      "number": "BT31-021",
      "name": "Baby Janemba, the Wicked",
      "rarity": "C",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-022",
      "number": "BT31-022",
      "name": "Baby Janemba, Hell Gate Agent of Destruction",
      "rarity": "R",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-023",
      "number": "BT31-023",
      "name": "Janemba, Cyborg Body",
      "rarity": "R",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-024",
      "number": "BT31-024",
      "name": "Power Release",
      "rarity": "R",
      "color": "Red",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-025",
      "number": "BT31-025",
      "name": "Buying Time",
      "rarity": "C",
      "color": "Red",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-026",
      "number": "BT31-026",
      "name": "Hellish Fusion",
      "rarity": "UC",
      "color": "Red",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-027",
      "number": "BT31-027",
      "name": "Monaka",
      "rarity": "UC",
      "color": "Blue",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-028",
      "number": "BT31-028",
      "name": "Krillin, Concerned for a God",
      "rarity": "R",
      "color": "Blue",
      "type": "Z-UNISON",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-029",
      "number": "BT31-029",
      "name": "Son Goku, Battle of the Strongest",
      "rarity": "C",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-030",
      "number": "BT31-030",
      "name": "Son Goku, Thrill of the Fight",
      "rarity": "C",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-031",
      "number": "BT31-031",
      "name": "Vegeta, Concerned for a God",
      "rarity": "SR",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-032",
      "number": "BT31-032",
      "name": "Piccolo, Wooden Actor",
      "rarity": "R",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-032_PR",
      "number": "BT31-032_PR",
      "name": "Piccolo, Wooden Actor",
      "rarity": "SPR",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-033",
      "number": "BT31-033",
      "name": "Beerus, God of Destruction’s Pride",
      "rarity": "R",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-033_PR",
      "number": "BT31-033_PR",
      "name": "Beerus, God of Destruction’s Pride",
      "rarity": "SPR",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-034",
      "number": "BT31-034",
      "name": "Monaka, Hidden Power",
      "rarity": "C",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-035",
      "number": "BT31-035",
      "name": "Monaka, Fathomless Power",
      "rarity": "C",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-036",
      "number": "BT31-036",
      "name": "Whis, the Glutton",
      "rarity": "UC",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-037",
      "number": "BT31-037",
      "name": "Beerus?, Inhibition",
      "rarity": "UC",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-038",
      "number": "BT31-038",
      "name": "Monaka, Business as Usual",
      "rarity": "SR",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-039",
      "number": "BT31-039",
      "name": "Monaka, an Unexpected Reunion",
      "rarity": "C",
      "color": "Blue",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-040",
      "number": "BT31-040",
      "name": "Conflict",
      "rarity": "UC",
      "color": "Blue",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-041",
      "number": "BT31-041",
      "name": "SS4 Son Goku & SS4 Vegeta",
      "rarity": "UC",
      "color": "Green",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-041_PR",
      "number": "BT31-041_PR",
      "name": "SS4 Son Goku & SS4 Vegeta",
      "rarity": "SLR",
      "color": "Green",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-042",
      "number": "BT31-042",
      "name": "Ultimate Fusion",
      "rarity": "C",
      "color": "Green",
      "type": "Z-EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-043",
      "number": "BT31-043",
      "name": "Pan, Adorable Supporter",
      "rarity": "C",
      "color": "Green",
      "type": "UNISON",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-043_SPR",
      "number": "BT31-043_SPR",
      "name": "Pan, Adorable Supporter",
      "rarity": "SPR",
      "color": "Green",
      "type": "UNISON",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-044",
      "number": "BT31-044",
      "name": "SS4 Son Goku, Vow of Victory",
      "rarity": "R",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-044_SPR",
      "number": "BT31-044_SPR",
      "name": "SS4 Son Goku, Vow of Victory",
      "rarity": "SPR",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-045",
      "number": "BT31-045",
      "name": "SS4 Son Goku, Gallant in Red",
      "rarity": "UC",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-046",
      "number": "BT31-046",
      "name": "SS4 Son Goku, Becoming the Strongest",
      "rarity": "C",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-047",
      "number": "BT31-047",
      "name": "SS4 Son Goku & SS4 Vegeta, Hopes Intertwined",
      "rarity": "R",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-048",
      "number": "BT31-048",
      "name": "Son Gohan, Bringer of Hope",
      "rarity": "UC",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-049",
      "number": "BT31-049",
      "name": "SS4 Vegeta, Vow of Victory",
      "rarity": "SR",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-050",
      "number": "BT31-050",
      "name": "SS4 Vegeta, Gallant in Red",
      "rarity": "UC",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-051",
      "number": "BT31-051",
      "name": "SS4 Vegeta, Becoming the Strongest",
      "rarity": "C",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-052",
      "number": "BT31-052",
      "name": "SS4 Gogeta, the Light Protecting the Universe",
      "rarity": "R",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-052_SPR",
      "number": "BT31-052_SPR",
      "name": "SS4 Gogeta, the Light Protecting the Universe",
      "rarity": "SPR",
      "color": "Green",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-053",
      "number": "BT31-053",
      "name": "Big Bang Kamehameha",
      "rarity": "SR",
      "color": "Green",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-054",
      "number": "BT31-054",
      "name": "The Mightiest Warrior’s Power",
      "rarity": "R",
      "color": "Green",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-055",
      "number": "BT31-055",
      "name": "Launch",
      "rarity": "UC",
      "color": "Yellow",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-055_PR",
      "number": "BT31-055_PR",
      "name": "Launch",
      "rarity": "SLR",
      "color": "Yellow",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-056",
      "number": "BT31-056",
      "name": "Commeson",
      "rarity": "UC",
      "color": "Yellow",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-056_PR",
      "number": "BT31-056_PR",
      "name": "Commeson",
      "rarity": "SLR",
      "color": "Yellow",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-057",
      "number": "BT31-057",
      "name": "Play-by-Play Announcer",
      "rarity": "C",
      "color": "Yellow",
      "type": "Z-BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-058",
      "number": "BT31-058",
      "name": "SS3 Gotenks, Soul Breaker",
      "rarity": "UC",
      "color": "Yellow",
      "type": "UNISON",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-059",
      "number": "BT31-059",
      "name": "Krillin, Challenge",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-060",
      "number": "BT31-060",
      "name": "Yamcha, Challenge",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-061",
      "number": "BT31-061",
      "name": "Tien Shinhan, Challenge",
      "rarity": "R",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-061_SPR",
      "number": "BT31-061_SPR",
      "name": "Tien Shinhan, Challenge",
      "rarity": "SPR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-062",
      "number": "BT31-062",
      "name": "Chiaotzu, Challenge",
      "rarity": "R",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-063",
      "number": "BT31-063",
      "name": "Master Roshi, Contest Spectator",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-064",
      "number": "BT31-064",
      "name": "Bulma, Contest Spectator",
      "rarity": "UC",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-065",
      "number": "BT31-065",
      "name": "Chi-Chi",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-066",
      "number": "BT31-066",
      "name": "Launch, Violent Personality",
      "rarity": "R",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-066_SPR",
      "number": "BT31-066_SPR",
      "name": "Launch, Violent Personality",
      "rarity": "SPR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-067",
      "number": "BT31-067",
      "name": "Launch, Gentle Personality",
      "rarity": "UC",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-067_SPR",
      "number": "BT31-067_SPR",
      "name": "Launch, Gentle Personality",
      "rarity": "SPR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-068",
      "number": "BT31-068",
      "name": "Launch, Here to Support",
      "rarity": "UC",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-069",
      "number": "BT31-069",
      "name": "Turtle, Contest Spectator",
      "rarity": "UC",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-070",
      "number": "BT31-070",
      "name": "Vegeta, the Targeted Prince",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-071",
      "number": "BT31-071",
      "name": "Vegeta, Backup From Afar",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-072",
      "number": "BT31-072",
      "name": "Jaco, Audience with an Elite",
      "rarity": "SR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-073",
      "number": "BT31-073",
      "name": "Commeson, Power Absorber",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-074",
      "number": "BT31-074",
      "name": "Commeson, Skill Absorber",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-074_SPR",
      "number": "BT31-074_SPR",
      "name": "Commeson, Skill Absorber",
      "rarity": "SPR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-075",
      "number": "BT31-075",
      "name": "SSB (Duplicate) Vegeta, Perfect Copy",
      "rarity": "SR",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-076",
      "number": "BT31-076",
      "name": "(Duplicate) Vegeta, Unchanging Instincts",
      "rarity": "R",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-077",
      "number": "BT31-077",
      "name": "(Duplicate) Vegeta, Rival Seeker",
      "rarity": "R",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-078",
      "number": "BT31-078",
      "name": "Gryll, Wanted Fugitive",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-079",
      "number": "BT31-079",
      "name": "Fused Zamasu, Embodiment of Despair",
      "rarity": "UC",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-080",
      "number": "BT31-080",
      "name": "Zamasu, Executing the Plan",
      "rarity": "C",
      "color": "Yellow",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-081",
      "number": "BT31-081",
      "name": "Transformed by a Sneeze",
      "rarity": "R",
      "color": "Yellow",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-082",
      "number": "BT31-082",
      "name": "Superhuman Water Unleashed",
      "rarity": "R",
      "color": "Yellow",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-083",
      "number": "BT31-083",
      "name": "Superhuman Water’s Threat",
      "rarity": "C",
      "color": "Yellow",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-084",
      "number": "BT31-084",
      "name": "Key to the Seal",
      "rarity": "UC",
      "color": "Yellow",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-085",
      "number": "BT31-085",
      "name": "Vegito",
      "rarity": "UC",
      "color": "Black",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-085_PR",
      "number": "BT31-085_PR",
      "name": "Vegito",
      "rarity": "SLR",
      "color": "Black",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-086",
      "number": "BT31-086",
      "name": "Aeos",
      "rarity": "UC",
      "color": "Black",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-086_PR",
      "number": "BT31-086_PR",
      "name": "Aeos",
      "rarity": "SLR",
      "color": "Black",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-087",
      "number": "BT31-087",
      "name": "Chronoa, God’s Power Stolen",
      "rarity": "C",
      "color": "Black",
      "type": "Z-UNISON",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-088",
      "number": "BT31-088",
      "name": "Son Goku & Vegeta, Warriors United",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-089",
      "number": "BT31-089",
      "name": "Son Goku & Vegeta, Interdimensional Warriors United",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-090",
      "number": "BT31-090",
      "name": "SSB Vegito, Azure Flash",
      "rarity": "SR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-091",
      "number": "BT31-091",
      "name": "SSB Vegito, Fusion Surpassing the Legends",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-092",
      "number": "BT31-092",
      "name": "Vegito, the Mightiest Fusion",
      "rarity": "UC",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-093",
      "number": "BT31-093",
      "name": "SS4 Limit Breaker Vegito, Crimson Flash, Super Full Power",
      "rarity": "SR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-094",
      "number": "BT31-094",
      "name": "SS4 Vegito, Dimension Transcending Peerless Warrior",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-095",
      "number": "BT31-095",
      "name": "SS3 Vegito, Unparalleled Power",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-096",
      "number": "BT31-096",
      "name": "SS Vegito, Dimension Transcending Fusion Warrior",
      "rarity": "UC",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-097",
      "number": "BT31-097",
      "name": "Chronoa, Supporting Her Predecessor",
      "rarity": "SR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-098",
      "number": "BT31-098",
      "name": "Chronoa & Aeos, Gods United",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-098_SPR",
      "number": "BT31-098_SPR",
      "name": "Chronoa & Aeos, Gods United",
      "rarity": "SPR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-099",
      "number": "BT31-099",
      "name": "Aeos, Supporting Her Successor",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-100",
      "number": "BT31-100",
      "name": "Aeos, Majesty of the Predecessors",
      "rarity": "UC",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-101",
      "number": "BT31-101",
      "name": "Aeos, Time Mender",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-102",
      "number": "BT31-102",
      "name": "Warrior in Black, Thirst for Power",
      "rarity": "UC",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-103",
      "number": "BT31-103",
      "name": "Future Warrior in Black, Thirst for Power",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-104",
      "number": "BT31-104",
      "name": "Namekian in Black, Thirst for Power",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-105",
      "number": "BT31-105",
      "name": "Female Warrior in Black, Thirst for Power",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-106",
      "number": "BT31-106",
      "name": "Crimson-Masked Saiyan, Power of Vengeance",
      "rarity": "SR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-107",
      "number": "BT31-107",
      "name": "Janemba, Dark Demon",
      "rarity": "R",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-108",
      "number": "BT31-108",
      "name": "Janemba, Rakshasa",
      "rarity": "C",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-109",
      "number": "BT31-109",
      "name": "Full-Strength Attack",
      "rarity": "C",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-110",
      "number": "BT31-110",
      "name": "United Across Time",
      "rarity": "C",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-110_SPR",
      "number": "BT31-110_SPR",
      "name": "United Across Time",
      "rarity": "SPR",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-111",
      "number": "BT31-111",
      "name": "Time’s Judgment",
      "rarity": "UC",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-112",
      "number": "BT31-112",
      "name": "Dimensional Transfer",
      "rarity": "R",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-113",
      "number": "BT31-113",
      "name": "Scroll of Time",
      "rarity": "C",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-114",
      "number": "BT31-114",
      "name": "Time Destruction",
      "rarity": "UC",
      "color": "Black",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-115",
      "number": "BT31-115",
      "name": "Training in the Hyperbolic Time Chamber",
      "rarity": "UC",
      "color": "White",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-115_SPR",
      "number": "BT31-115_SPR",
      "name": "Training in the Hyperbolic Time Chamber",
      "rarity": "SLR",
      "color": "White",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-116",
      "number": "BT31-116",
      "name": "Cell",
      "rarity": "UC",
      "color": "White",
      "type": "LEADER",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-116_PR",
      "number": "BT31-116_PR",
      "name": "Cell",
      "rarity": "SLR",
      "color": "White",
      "type": "LEADER",
      "variant": "Special Leader Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-117",
      "number": "BT31-117",
      "name": "Android 16, Advice",
      "rarity": "UC",
      "color": "White",
      "type": "Z-UNISON",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-118",
      "number": "BT31-118",
      "name": "SS2 Son Gohan, Awakened Form",
      "rarity": "SR",
      "color": "White",
      "type": "Z-BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-119",
      "number": "BT31-119",
      "name": "Cell, Creeping Terror",
      "rarity": "R",
      "color": "White",
      "type": "Z-BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-120",
      "number": "BT31-120",
      "name": "SS Son Goku, Training in the Chamber",
      "rarity": "UC",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-121",
      "number": "BT31-121",
      "name": "SS Son Gohan, Training in the Chamber",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-122",
      "number": "BT31-122",
      "name": "SS Son Gohan, Result of Training",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-123",
      "number": "BT31-123",
      "name": "SS Vegeta, Training in the Chamber",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-124",
      "number": "BT31-124",
      "name": "SS Trunks, Training in the Chamber",
      "rarity": "SR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-125",
      "number": "BT31-125",
      "name": "Bulma, Training Assistant",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-126",
      "number": "BT31-126",
      "name": "Android 18, Supporter",
      "rarity": "UC",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-127",
      "number": "BT31-127",
      "name": "Dende, Training Assistant",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-128",
      "number": "BT31-128",
      "name": "Cell, Ultimate Form",
      "rarity": "SR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-129",
      "number": "BT31-129",
      "name": "Cell, Perfect Form",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-130",
      "number": "BT31-130",
      "name": "Cell, Absorbed Form",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-131",
      "number": "BT31-131",
      "name": "Cell, Ominous Android",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-131_SPR",
      "number": "BT31-131_SPR",
      "name": "Cell, Ominous Android",
      "rarity": "SPR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-132",
      "number": "BT31-132",
      "name": "Cell, Ominous Larva",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-133",
      "number": "BT31-133",
      "name": "Cell Jr., the Fiendish",
      "rarity": "SR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-134",
      "number": "BT31-134",
      "name": "SS3 Gotenks, Secret Fusion",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-135",
      "number": "BT31-135",
      "name": "Piccolo, Sealed in the Chamber",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-136",
      "number": "BT31-136",
      "name": "Hercule, the World’s Hope",
      "rarity": "C",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-137",
      "number": "BT31-137",
      "name": "Majin Buu, Fear Incarnate",
      "rarity": "R",
      "color": "White",
      "type": "BATTLE",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-137_SPR",
      "number": "BT31-137_SPR",
      "name": "Majin Buu, Fear Incarnate",
      "rarity": "SPR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Special Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-138",
      "number": "BT31-138",
      "name": "Cell’s Solar Flare",
      "rarity": "UC",
      "color": "White",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-139",
      "number": "BT31-139",
      "name": "Absorb and Power Up",
      "rarity": "C",
      "color": "White",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-140",
      "number": "BT31-140",
      "name": "Regeneration Skill",
      "rarity": "UC",
      "color": "White",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-141",
      "number": "BT31-141",
      "name": "Cell Jr. Summon",
      "rarity": "C",
      "color": "White",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-142",
      "number": "BT31-142",
      "name": "Cell’s Kamehameha",
      "rarity": "UC",
      "color": "White",
      "type": "EXTRA",
      "variant": "Regular",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-143",
      "number": "BT31-143",
      "name": "SS Gogeta, Ultimate Warrior",
      "rarity": "CR",
      "color": "Red",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-144",
      "number": "BT31-144",
      "name": "SSB Gogeta, Ultimate Warrior",
      "rarity": "CR",
      "color": "Blue",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-145",
      "number": "BT31-145",
      "name": "SS4 Gogeta, Ultimate Warrior",
      "rarity": "CR",
      "color": "Green",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-146",
      "number": "BT31-146",
      "name": "SS Vegito, Ultimate Warrior",
      "rarity": "CR",
      "color": "Yellow",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-147",
      "number": "BT31-147",
      "name": "SSB Vegito, Ultimate Warrior",
      "rarity": "CR",
      "color": "Black",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-148",
      "number": "BT31-148",
      "name": "SS3 Gotenks, Ultimate Warrior",
      "rarity": "CR",
      "color": "White",
      "type": "UNISON",
      "variant": "Concept Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-149",
      "number": "BT31-149",
      "name": "SS Gogeta, Hell-Piercing Flash",
      "rarity": "SCR",
      "color": "Red",
      "type": "BATTLE",
      "variant": "Secret Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-150",
      "number": "BT31-150",
      "name": "SSB Kaio-ken Vegito, True God Power",
      "rarity": "SCR",
      "color": "Black",
      "type": "BATTLE",
      "variant": "Secret Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-151",
      "number": "BT31-151",
      "name": "SS Vegito & SS3 Gotenks, Fusion Warrior at Battle’s End",
      "rarity": "SCR",
      "color": "White",
      "type": "BATTLE",
      "variant": "Secret Rare",
      "verified": true,
      "group": "main"
    },
    {
      "id": "BT31-151_GDR",
      "number": "BT31-151_GDR",
      "name": "SS Vegito & SS3 Gotenks, Fusion Warrior at Battle’s End",
      "rarity": "GDR",
      "color": "White",
      "type": "BATTLE",
      "variant": "God Rare",
      "verified": true,
      "group": "main"
    }
  ]
};
